// design-system.json ↔ tokens.css ↔ 신호의 정답지 사이를 잇는다(원칙 1-2, DESIGN 4-1).
// 도트경로(color.brand.primary)를 케밥 CSS 변수(--color-brand-primary)로 평탄화.

/** camelCase / 단어 한 토막을 케밥으로. (토큰 키는 대부분 단어 한 토막이지만 방어적으로) */
function kebab(seg) {
  return String(seg)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/\s+/g, '-')
    .toLowerCase();
}

/** 중첩 토큰 객체를 { "color-brand-primary": "#2F6BFF", ... } 로 평탄화. */
export function flattenTokens(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}-${kebab(k)}` : kebab(k);
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      flattenTokens(v, key, out);
    } else {
      out[key] = v;
    }
  }
  return out;
}

/** 도트경로 하나를 design-system 에서 실제 값으로 resolve. 없으면 undefined. */
export function resolveToken(ds, dotPath) {
  return String(dotPath)
    .split('.')
    .reduce((o, k) => (o == null ? undefined : o[k]), ds);
}

/** components.json 의 tokens 배열을 { "color.bg.surface": "#0E0E10", ... } 로 resolve. */
export function resolveTokens(ds, dotPaths = []) {
  const r = {};
  for (const p of dotPaths) r[p] = resolveToken(ds, p);
  return r;
}

/**
 * design-system → tokens.css 문자열.
 * 전역 :root 가 아니라 .clone-root 에 깔아 스코프 격리(원칙 1-5 / DESIGN 4-1).
 */
export function emitTokensCss(ds, { selector = '.clone-root' } = {}) {
  const flat = flattenTokens(ds);
  const lines = Object.entries(flat).map(([k, v]) => `  --${k}: ${v};`);
  return `/* AUTO-GENERATED by assemble.mjs — design-system.json 에서 emit. 직접 수정 금지. */\n${selector} {\n${lines.join('\n')}\n}\n`;
}
