// export 어댑터: cafe24-skin
// 정적 통짜(cafe24-fragment)와 달리, 우리 "디자인"을 카페24 실제 스킨 마크업에 입히는 형태.
// 상품 그리드 마크업은 카페24 서버 모듈(module="product_ListItem" + {$변수})이 실제 상품으로 채우고,
// 우리는 그 모듈이 쓰는 실제 클래스(prdList__item·thumbnail·name·badge·spec…)를 타깃하는 CSS 를 emit 한다.
//
// 산출(dist/skin/):
//   tokens.css   : design-system.json → CSS 변수(.ph-skin 스코프)
//   skin.css     : 카페24 클래스 타깃 디자인 CSS(브랜드 무관, var(--token) 참조)
//   mockup.html  : .ph-skin + 카페24 클래스 + 샘플 상품(정적·data-component) → 채점 트윈(원칙 1-5)
//   INTEGRATION.md : 실제 skin 에 얹는 법
// auditEntry: skin/mockup.html (loop --audit 이 이걸 렌더해 재채점)
import fs from 'node:fs';
import path from 'node:path';
import { emitTokensCss } from '../lib/tokens.mjs';

export const id = 'cafe24-skin';

// 카페24 표준 상품 클래스(prdList__item/thumbnail/name/spec/badge…)를 타깃하는 디자인 CSS.
// 우리가 만든 product-grid 의 룩을 카페24 마크업에 옮긴 것. 토큰은 var() 로 참조 → 브랜드 무관.
const SKIN_CSS = `/* AUTO-GENERATED by cafe24-skin adapter. design 토큰을 카페24 실제 클래스에 입힌다. */
.ph-skin { font-family: var(--type-family-body); color: var(--color-text-primary); }
.ph-skin *, .ph-skin *::before, .ph-skin *::after { box-sizing: border-box; }

/* 섹션 헤더(상품 그룹 타이틀) */
.ph-skin .ph-section { padding: var(--space-section) max((100% - 1200px)/2, var(--space-lg)); }
.ph-skin .ph-section__head { display: flex; align-items: baseline; justify-content: space-between; margin-bottom: var(--space-lg); }
.ph-skin .ph-section__head h2 { margin: 0; font-family: var(--type-family-heading); font-size: var(--type-size-h2); font-weight: var(--type-weight-extrabold); }
.ph-skin .ph-section__head .more { color: var(--color-text-muted); font-size: var(--type-size-sm); text-decoration: none; }

/* 상품 리스트 — 카페24 .prdList / .prdList__item 타깃 */
.ph-skin .prdList { display: grid; grid-template-columns: repeat(5, 1fr); gap: var(--space-gridgap); list-style: none; margin: 0; padding: 0; }
.ph-skin .prdList__item { display: flex; flex-direction: column; position: relative; }
.ph-skin .prdList__item .thumbnail { position: relative; display: block; aspect-ratio: 1 / 1; margin-bottom: var(--space-cardgap); border-radius: var(--radius-card); overflow: hidden; background-color: var(--color-bg-thumb); border: 1px solid var(--color-border-default); box-shadow: var(--shadow-card); }
.ph-skin .prdList__item .thumbnail img { width: 100%; height: 100%; object-fit: cover; display: block; }
.ph-skin .prdList__item .badge { position: absolute; top: 8px; left: 8px; z-index: 2; background: var(--color-semantic-sale); color: #fff; font-size: var(--type-size-caption); font-weight: var(--type-weight-bold); padding: 3px 9px; border-radius: var(--radius-sm); box-shadow: var(--shadow-sm); }
.ph-skin .prdList__item .badge.is-promo { background: var(--color-semantic-promo); color: #1c1407; }
.ph-skin .prdList__item .badge.is-new { background: var(--color-semantic-new); }
.ph-skin .prdList__item .effect { align-self: flex-start; font-size: var(--type-size-caption); margin-bottom: 4px; padding: 1px 7px; border-radius: var(--radius-sm); background: var(--color-semantic-newbg); color: var(--color-brand-dark); }
.ph-skin .prdList__item .name { margin: 0 0 4px; font-size: var(--type-size-body); font-weight: var(--type-weight-medium); color: var(--color-text-primary); }
.ph-skin .prdList__item .description { font-size: var(--type-size-caption); color: var(--color-text-muted); }
.ph-skin .prdList__item .spec { margin-top: 4px; }
.ph-skin .prdList__item .spec .price-was { margin-right: 6px; color: var(--color-text-muted); font-size: var(--type-size-caption); text-decoration: line-through; }
.ph-skin .prdList__item .spec .price { font-size: var(--type-size-body); font-weight: var(--type-weight-extrabold); color: var(--color-brand-primary); }
.ph-skin .prdList__item .wish, .ph-skin .prdList__item .cart { position: absolute; bottom: 10px; right: 10px; z-index: 2; }

/* 헤더/푸터 섹션 (서버모듈 아님 — 레이아웃 파일에 들어감) */
.ph-skin .ph-header { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-md); padding: 14px max((100% - 1200px)/2, var(--space-lg)); background: var(--color-bg-page); border-bottom: 1px solid var(--color-border-default); }
.ph-skin .ph-header .logo { font-family: var(--type-family-heading); font-size: var(--type-size-h2); font-weight: var(--type-weight-extrabold); color: var(--color-brand-primary); text-decoration: none; }
.ph-skin .ph-header .search { flex: 1 1 360px; display: flex; align-items: center; padding: 0 6px 0 var(--space-md); background: var(--color-bg-muted); border: 2px solid var(--color-brand-primary); border-radius: var(--radius-pill); }
.ph-skin .ph-header .search input { flex: 1; border: 0; background: transparent; outline: 0; padding: 11px 0; font-size: var(--type-size-body); }
.ph-skin .ph-header .gnb { flex-basis: 100%; display: flex; gap: var(--space-lg); }
.ph-skin .ph-header .gnb a { color: var(--color-text-primary); text-decoration: none; font-weight: var(--type-weight-medium); }
.ph-skin .ph-footer { background: var(--color-bg-surface); color: var(--color-text-invmuted); padding: var(--space-xl) max((100% - 1200px)/2, var(--space-lg)); font-size: var(--type-size-caption); }
`;

// 카페24 모듈 마크업(납품용) — 실제 상품을 서버가 채운다. 우리 CSS(skin.css)가 .prdList__item… 를 입힌다.
const LIST_PRODUCT_TEMPLATE = `<!-- list_product.html (카페24 모듈) — skin.css 가 스타일을 입힌다. {$변수}는 서버가 채움 -->
<ul class="prdList" module="product_ListItem">
  <li class="prdList__item" id="anchorBoxId_{$product_no}">
    <a class="thumbnail" href="{$link_product_detail}">
      <img src="{$image_medium}" alt="{$product_name}" />
      <span class="badge is-promo" module="product_Imagestyle">{$benefit_icons}</span>
    </a>
    <div class="description">
      <p class="name"><a href="{$link_product_detail}">{$product_name}</a></p>
      <div class="spec">{$product_price}</div>
    </div>
  </li>
</ul>`;

function sampleCard(i, img) {
  const sets = [
    { badge: 'badge', tag: '34%↓', eff: '눈 건강', name: '루테인 지아잔틴', was: '28,000', price: '18,900원' },
    { badge: 'badge is-promo', tag: '한정', eff: '피부 탄력', name: '저분자 콜라겐', was: '42,000', price: '32,900원' },
    { badge: 'badge is-new', tag: 'NEW', eff: '하루 영양', name: '멀티비타민 미네랄', was: '33,000', price: '23,900원' },
    { badge: 'badge', tag: '31%↓', eff: '장 건강', name: '프로바이오틱스 100억', was: '35,000', price: '24,900원' },
    { badge: 'badge is-promo', tag: '1+1', eff: '혈행 개선', name: '알티지 오메가3', was: '39,000', price: '29,900원' },
  ];
  const s = sets[i % sets.length];
  return `    <li class="prdList__item" data-role="card">
      <span class="thumbnail"><img src="${img}" alt="${s.name}" /><span class="${s.badge}">${s.tag}</span></span>
      <div class="description">
        <span class="effect">${s.eff}</span>
        <p class="name">${s.name}</p>
        <div class="spec"><span class="price-was">${s.was}</span><span class="price">${s.price}</span></div>
      </div>
    </li>`;
}

export async function run({ runName, paths }) {
  const ds = JSON.parse(fs.readFileSync(paths.designSystem, 'utf8'));
  const skinDir = path.join(paths.dist, 'skin');
  fs.mkdirSync(skinDir, { recursive: true });

  // 1) tokens.css (.ph-skin 스코프)
  const tokensCss = emitTokensCss(ds, { selector: '.ph-skin' });
  fs.writeFileSync(path.join(skinDir, 'tokens.css'), tokensCss, 'utf8');

  // 2) skin.css (카페24 클래스 타깃)
  fs.writeFileSync(path.join(skinDir, 'skin.css'), SKIN_CSS, 'utf8');

  // 3) list_product.html (납품용 모듈 마크업)
  fs.mkdirSync(path.join(skinDir, 'product'), { recursive: true });
  fs.writeFileSync(path.join(skinDir, 'product', 'list_product.html'), LIST_PRODUCT_TEMPLATE, 'utf8');

  // 샘플 이미지: 런의 src/assets 가 있으면 dist/skin/assets 로 복사, 없으면 placehold.co
  const srcAssets = path.join(paths.src, 'assets');
  let imgs;
  if (fs.existsSync(srcAssets)) {
    const dstAssets = path.join(skinDir, 'assets');
    fs.mkdirSync(dstAssets, { recursive: true });
    const files = fs.readdirSync(srcAssets).filter((f) => /\.(jpg|jpeg|png|webp)$/i.test(f));
    for (const f of files) fs.copyFileSync(path.join(srcAssets, f), path.join(dstAssets, f));
    const prod = files.filter((f) => /^p\d/.test(f));
    imgs = (prod.length ? prod : files).map((f) => `assets/${f}`);
  }
  if (!imgs || !imgs.length) imgs = Array.from({ length: 5 }, (_, i) => `https://placehold.co/600x600/EAF1EC/16A34A.png?text=PHYTO+${i + 1}`);

  // 4) mockup.html — 카페24 클래스 + 샘플 상품(정적·data-component) → 채점 트윈
  const cards = Array.from({ length: 10 }, (_, i) => sampleCard(i, imgs[i % imgs.length])).join('\n');
  const mockup = `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>cafe24-skin mockup · ${runName}</title>
<link rel="stylesheet" href="tokens.css">
<link rel="stylesheet" href="skin.css">
</head>
<body>
<div class="ph-skin">
  <header class="ph-header" data-component="header" data-role="header">
    <a class="logo" data-role="logo" href="#">PHYTO<span>TECH</span></a>
    <form class="search" data-role="search"><input type="search" placeholder="건강기능식품·성분으로 검색" aria-label="검색"></form>
    <nav class="gnb" data-role="nav"><a>신상품</a><a>베스트</a><a>비타민</a><a>정기구독</a><a>이벤트</a></nav>
  </header>

  <section class="ph-section" data-component="product-grid" data-role="section">
    <div class="ph-section__head"><h2 data-role="section-title">이주의 베스트</h2><a class="more" href="#">더보기 +</a></div>
    <ul class="prdList">
${cards}
    </ul>
  </section>

  <footer class="ph-footer" data-component="footer" data-role="footer">
    (주)피토테크 · 고객센터 1588-0000 · © 2026 PHYTOTECH. All rights reserved.
  </footer>
</div>
</body>
</html>
`;
  fs.writeFileSync(path.join(skinDir, 'mockup.html'), mockup, 'utf8');

  // 5) 통합 가이드
  const guide = `# cafe24-skin 통합 가이드 (${runName})

이 어댑터는 "정적 조각"이 아니라 **카페24 스킨에 얹는 디자인 레이어**를 emit 한다.

## 파일
- tokens.css : 디자인 토큰(CSS 변수, .ph-skin 스코프)
- skin.css   : 카페24 실제 클래스(prdList__item·thumbnail·name·badge·spec…) 타깃 디자인 CSS
- product/list_product.html : 상품 그리드 모듈 마크업 예시(서버가 {$변수}로 실제 상품 채움)
- mockup.html : 채점/미리보기용 트윈(샘플 상품, 정적)

## 적용
1. tokens.css + skin.css 를 스킨에 추가(예: layout/basic/css/ 에 두고 \`<!--@css(...)-->\` 로 로드).
2. 스킨 본문(또는 섹션)을 \`<div class="ph-skin"> … </div>\` 로 감싼다(전역 충돌 방지).
3. 상품 그리드는 카페24 모듈 그대로 두되, 마크업이 .prdList__item / .thumbnail / .name / .badge / .spec .price
   클래스를 쓰도록 맞춘다(대부분 기본 스킨이 이미 사용). 그러면 skin.css 가 우리 디자인을 입힌다.
4. 실제 상품은 서버가 자동으로 채운다 — 정적 카드 불필요.

## 주의(원칙 1-5)
- 납품물은 {$변수} 모듈이라 카페24 서버에서만 렌더된다. 로컬 채점은 mockup.html(트윈)으로 한다.
- 색/치수/위계는 design 토큰이 진실 원천. 토큰만 바꾸면 스킨 전체 룩이 따라온다.
`;
  fs.writeFileSync(path.join(skinDir, 'INTEGRATION.md'), guide, 'utf8');

  return {
    outputs: [
      { path: path.join(skinDir, 'skin.css'), label: '카페24 클래스 타깃 디자인 CSS' },
      { path: path.join(skinDir, 'tokens.css'), label: '디자인 토큰' },
      { path: path.join(skinDir, 'product', 'list_product.html'), label: '상품 모듈 마크업' },
      { path: path.join(skinDir, 'mockup.html'), label: '채점/미리보기 트윈' },
      { path: path.join(skinDir, 'INTEGRATION.md'), label: '통합 가이드' },
    ],
    auditEntry: 'skin/mockup.html',
  };
}
