// export 어댑터: cafe24-skin
// 우리 "디자인"을 카페24 실제 스킨에 얹는 형태. 두 가지를 같이 emit 한다:
//   (A) 실제 납품용 — 카페24 표준 클래스(prdList__item·thumbnail·name·badge·spec .price) 타깃 CSS + 모듈 마크업.
//       상품 그리드는 카페24 서버 모듈(module="product_ListItem" + {$변수})이 실제 상품으로 채우고, 우리 CSS 가 입힌다.
//   (B) 채점 트윈 — 이 run 의 조립 페이지(9개 data-component) 전체를 .ph-skin 스코프로 옮긴 mockup.html.
//       {$변수}는 서버에서만 렌더되므로, 로컬 채점은 이 트윈으로 한다(원칙 1-5). loop --audit 이 9개 전부 재채점.
//
// 산출(dist/skin/): tokens.css · skin.css · product/list_product.html · mockup.html · INTEGRATION.md
import fs from 'node:fs';
import path from 'node:path';
import { emitTokensCss } from '../lib/tokens.mjs';

export const id = 'cafe24-skin';

// 실제 납품용: 카페24 표준 상품 클래스 타깃(브랜드 무관, var(--token)). 서버 모듈 마크업에 디자인을 입힌다.
const CAFE24_PRODUCT_CSS = `
/* ── 카페24 표준 상품 클래스 타깃(실제 납품: 서버 모듈이 채우는 .prdList__item 에 디자인 입힘) ── */
.ph-skin .prdList { display: grid; grid-template-columns: repeat(5, 1fr); gap: var(--space-gridgap); list-style: none; margin: 0; padding: 0; }
.ph-skin .prdList__item { display: flex; flex-direction: column; position: relative; }
.ph-skin .prdList__item .thumbnail { position: relative; display: block; aspect-ratio: 1/1; margin-bottom: var(--space-cardgap); border-radius: var(--radius-card); overflow: hidden; background-color: var(--color-bg-thumb); border: 1px solid var(--color-border-default); box-shadow: var(--shadow-card); }
.ph-skin .prdList__item .thumbnail img { width: 100%; height: 100%; object-fit: cover; display: block; }
.ph-skin .prdList__item .badge { position: absolute; top: 8px; left: 8px; z-index: 2; background: var(--color-semantic-sale); color: #fff; font-size: var(--type-size-caption); font-weight: var(--type-weight-bold); padding: 3px 9px; border-radius: var(--radius-sm); box-shadow: var(--shadow-sm); }
.ph-skin .prdList__item .badge.is-promo { background: var(--color-semantic-promo); color: #1c1407; }
.ph-skin .prdList__item .badge.is-new { background: var(--color-semantic-new); }
.ph-skin .prdList__item .name { margin: 8px 0 4px; font-size: var(--type-size-body); font-weight: var(--type-weight-medium); color: var(--color-text-primary); }
.ph-skin .prdList__item .spec { font-size: var(--type-size-caption); color: var(--color-text-muted); }
.ph-skin .prdList__item .spec .price { font-size: var(--type-size-body); font-weight: var(--type-weight-extrabold); color: var(--color-brand-primary); }
.ph-skin .prdList__item .spec .price-was { margin-right: 6px; text-decoration: line-through; color: var(--color-text-muted); }
`;

const LIST_PRODUCT_TEMPLATE = `<!-- list_product.html (카페24 모듈) — skin.css 가 .prdList__item 에 디자인을 입힌다. {$변수}는 서버가 채움 -->
<ul class="prdList" module="product_ListItem">
  <li class="prdList__item" id="anchorBoxId_{$product_no}">
    <a class="thumbnail" href="{$link_product_detail}">
      <img src="{$image_medium}" alt="{$product_name}" />
      <span class="badge is-promo" module="product_Imagestyle">{$benefit_icons}</span>
    </a>
    <div class="description">
      <p class="name"><a href="{$link_product_detail}">{$product_name}</a></p>
      <div class="spec">{$product_price}</div>
    </div>
  </li>
</ul>`;

function read(file) {
  return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
}

export async function run({ runName, paths }) {
  if (!fs.existsSync(paths.index)) {
    throw new Error(`export(cafe24-skin): ${paths.index} 가 없음. 먼저 assemble 을 돌리세요.`);
  }
  const ds = JSON.parse(fs.readFileSync(paths.designSystem, 'utf8'));
  const skinDir = path.join(paths.dist, 'skin');
  fs.mkdirSync(skinDir, { recursive: true });

  // 1) tokens.css — design 토큰을 .ph-skin 스코프 CSS 변수로
  fs.writeFileSync(path.join(skinDir, 'tokens.css'), emitTokensCss(ds, { selector: '.ph-skin' }), 'utf8');

  // 2) skin.css — 이 run 의 styles.css 를 .clone-root → .ph-skin 으로 재스코프 + 카페24 상품 클래스 타깃 CSS(납품용)
  const stylesCss = read(paths.stylesCss);
  const rescoped = stylesCss.split('.clone-root').join('.ph-skin');
  fs.writeFileSync(
    path.join(skinDir, 'skin.css'),
    `/* AUTO-GENERATED by cafe24-skin. (A) 런의 디자인 CSS(.ph-skin 재스코프) + (B) 카페24 표준 클래스 타깃 */\n${rescoped}\n${CAFE24_PRODUCT_CSS}`,
    'utf8'
  );

  // 3) list_product.html — 납품용 카페24 모듈 마크업
  fs.mkdirSync(path.join(skinDir, 'product'), { recursive: true });
  fs.writeFileSync(path.join(skinDir, 'product', 'list_product.html'), LIST_PRODUCT_TEMPLATE, 'utf8');

  // 런의 src/assets 를 dist/skin/assets 로 복사(트윈/미리보기 자급)
  const srcAssets = path.join(paths.src, 'assets');
  if (fs.existsSync(srcAssets)) {
    const dstAssets = path.join(skinDir, 'assets');
    fs.mkdirSync(dstAssets, { recursive: true });
    for (const f of fs.readdirSync(srcAssets)) {
      if (/\.(jpg|jpeg|png|webp|svg|gif)$/i.test(f)) fs.copyFileSync(path.join(srcAssets, f), path.join(dstAssets, f));
    }
  }

  // 4) mockup.html — 채점 트윈: 런의 조립 페이지(9개 data-component) 전체를 .ph-skin 스코프로
  const html = read(paths.index);
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const body = (bodyMatch ? bodyMatch[1] : html)
    .replace(/<script[^>]*src=[^>]*>\s*<\/script>/gi, '')
    .replace(/class="clone-root"/g, 'class="ph-skin"')
    .trim();
  const mockup = `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>cafe24-skin twin · ${runName}</title>
<link rel="stylesheet" href="tokens.css">
<link rel="stylesheet" href="skin.css">
</head>
<body>
${body}
</body>
</html>
`;
  fs.writeFileSync(path.join(skinDir, 'mockup.html'), mockup, 'utf8');

  // 5) 통합 가이드
  const guide = `# cafe24-skin 통합 가이드 (${runName})

우리 디자인을 카페24 실제 스킨에 얹는 레이어. "정적 통짜 조각"(cafe24-fragment)과 다르다.

## 파일
- tokens.css : 디자인 토큰(CSS 변수, .ph-skin 스코프)
- skin.css   : (A) 런의 디자인 CSS(.ph-skin 재스코프) + (B) 카페24 표준 클래스(prdList__item·thumbnail·name·badge·spec .price) 타깃
- product/list_product.html : 상품 그리드 모듈 마크업(서버가 {$변수}로 실제 상품 채움)
- mockup.html : 채점/미리보기 트윈 — 이 런의 컴포넌트 전체를 .ph-skin 스코프로 렌더(정적)

## 적용(기본)
1. tokens.css + skin.css 를 스킨에 추가(예: layout/basic/css/ 에 두고 \`<!--@css(...)-->\` 로 로드). phyto CSS 는 스킨 CSS '뒤'(마지막)에 로드해야 캐스케이드 우선.
2. 스킨 본문/섹션을 \`<div class="ph-skin"> … </div>\` 로 감싼다(전역 충돌 방지).
3. 상품 그리드는 카페24 모듈 그대로(클래스 .prdList__item/.thumbnail/.name/.badge/.spec .price) → skin.css 가 디자인을 입힘. 실제 상품은 서버가 채운다.

## 실전 매핑 플레이북 (실제 운영 스킨에 통합할 때 — 중요)
이 어댑터의 skin.css(B) 는 '카페24 표준 상품 클래스'를 가정한 출발점이다. 실제 스킨은 자기 고유 클래스/구조를 쓰므로
헤더·푸터·내비·플로팅·배너는 표준 클래스 가정만으로는 입혀지지 않는다. 다음을 지킨다(색·타이포·배지만, 레이아웃은 스킨 그대로):

1. 표준 클래스 가정 금지 → 영역별 실제 마크업에 매핑. 대상 스킨 HTML 을 열어 실제 클래스
   (예: #header, .top_category, #footer, .bt_util, #quick, .pageTop, main_3dan_banner, .main_banner_txt01 …)를 확인하고
   영역별 phyto-<area>.css 로 .ph-skin 스코프 타깃을 직접 작성한다.
2. 레이아웃 파일이 여러 개일 수 있다 → 컴포넌트가 렌더되는 레이아웃마다 @css 배선.
   예: 메인/리스트=layout.html, 상세=detail_layout.html. 플로팅(quick)이 detail_layout 에서만 @import 되면 그 CSS·토큰을 detail_layout 에도 로드.
3. 스마트디자인(ez) 인라인 스타일 주의 → 외부 CSS를 덮는다. ez 에디터가 박은 인라인 color/font-weight 가 우선하므로
   !important 로 소리없이 싸우지 말고, 잠긴 속성은 미선언 + '어드민에서 인라인 서식 제거'로 가이드한다.
4. 스마트배너 슬롯(@import 외부 배너)·이미지는 어드민 전용 → 스킨 CSS로 제어 불가.
   배너는 '스타일 가능한 텍스트/CTA 클래스'만 재스킨하고, 이미지·카피는 어드민 운영 가이드로 넘긴다.

→ 실제 사례: docs/CASE-STUDY-cafe24-skin3.md (PHYTOTECH → 운영 skin3 통합: header·footer·category·floating·banner).

## 채점(원칙 1-5)
- 납품물은 {$변수} 모듈이라 카페24 서버에서만 렌더 → 로컬 채점은 mockup.html 트윈으로.
- \`config.export.adapter\`를 "cafe24-skin"으로 두고 \`npm run loop -- ${runName} --audit\` → 컴포넌트 전부 재채점.
`;
  fs.writeFileSync(path.join(skinDir, 'INTEGRATION.md'), guide, 'utf8');

  return {
    outputs: [
      { path: path.join(skinDir, 'skin.css'), label: '카페24 스킨 CSS(재스코프+클래스 타깃)' },
      { path: path.join(skinDir, 'tokens.css'), label: '디자인 토큰' },
      { path: path.join(skinDir, 'product', 'list_product.html'), label: '상품 모듈 마크업' },
      { path: path.join(skinDir, 'mockup.html'), label: '9컴포넌트 채점 트윈' },
      { path: path.join(skinDir, 'INTEGRATION.md'), label: '통합 가이드' },
    ],
    auditEntry: 'skin/mockup.html',
  };
}
